services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=.:./app/db
      - DATA_DIR=/app/data
      - DUCKDB_PATH=/app/data/analytics.duckdb
      - DATA_FILE=/app/data/sample_data.csv
    volumes:
      - ./services/api/app:/app/app
      - ./services/api/requirements.txt:/app/requirements.txt
      - ./data:/app/data
      - ./services/api/scripts:/app/scripts
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
